apiVersion: skaffold/v1beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: gcr.io/skaff-jwtea/hello
      context: ./containers/hello
    - image: gcr.io/skaff-jwtea/site
      context: ./containers/site
test:
  - image: gcr.io/skaff-jwtea/hello
    structureTests:
      - "./structure-tests/*"
deploy:
  helm:
    releases:
      - name: exampleapp
        chartPath: helm
        #wait: true
        #valuesFiles:
        #- helm-skaffold-values.yaml
        #recreatePods will pass --recreate-pods to helm upgrade
        #recreatePods: true
        #overrides builds an override values.yaml file to run with the helm deploy
        #overrides:
        # some:
        #   key: someValue
        #setValues get appended to the helm deploy with --set.
        #setValues:
        #some.key: someValue
