apiVersion: v1
kind: Service
metadata:
  name: {{ template "exampleapp.fullname" . }}
  labels:
    app: {{ .Values.app.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.nginx.type }}
  ports:
    - port: {{ .Values.nginx.externalPort }}
      targetPort: {{ .Values.nginx.internalPort }}
      protocol: TCP
      name: {{ .Values.nginx.name }}
  selector:
    app: {{ .Values.app.name }}
    release: {{ .Release.Name }}